### ISSUE TITLE
WHMCS回调地址怎么填写

### ISSUE THREAD

**Issue by MiuKaShi** [tutugreen/WHMCS-JSJ-API-Pay-Gataway#1]
说是要修改自己的WHMCS回调地址
第74行这个怎么填写呀
	$JSJApiPay_config['return_url'] = "";

**Comment by tutugreen** [comment]
请参考[上方的注释](https://github.com/tutugreen/WHMCS-JSJ-API-Pay-Gataway/blob/master/JSJApiPay.php#L72)，填写为您的站点接口JSJApiPay_callback.php文件的URL。
