### ISSUE TITLE
网关通讯出现偏差，请重试

### ISSUE THREAD

**Issue by xosadmin** [tutugreen/WHMCS-JSJ-API-Pay-Gataway#12]
如题，我用的国外虚拟主机，对接好后测试支付宝支付时提示：网关通讯出现偏差，请重试。请问这是怎么回事呢？

**Comment by xnknown** [comment]
同样问题  请问 找到解决方案了吗？

**Comment by tutugreen** [comment]
先测试一下ssh下curl api地址是否正常返回。

如果返回不了，换个主机/网络，如果返回要3秒以上，到各接口PHP里把CURL TIMEOUT参数改大。

**Comment by tutugreen** [comment]
Hi，许久没收到回复。先Close啦~ 如果仍有问题的话可以再回复。
@xosadmin @xnknown
