### ISSUE TITLE
流水号编码规则能不能改？

### ISSUE THREAD

**Issue by icase** [tutugreen/WHMCS-JSJ-API-Pay-Gataway#2]
包含**JSJApiPay_alip**有点太明显，不想让流水编码规则有太明显的特征，这个可以自行调整么？

**Comment by tutugreen** [comment]
JSJApiPay可以去掉，只是方便查单分辨接口

回调编码规则参考：[http://api.web567.net/forum.php?mod=viewthread&tid=52&extra=page%3D1](官方说明)
